### ISSUE TITLE
Eco/BasicVent support

### ISSUE THREAD

**Issue by Polooo2** [sibbi77/openhab2-addons#1]
Hey hey,
nice that you picked up this binding to move it to Openhab 2/3. Last year Waterkotte added support to connect the Eco/BasicVent to the Ecotouch AND control it via the webpage/mobile app. 

Would be great if you could add these tags as well. 
From my system I got these (in German ;) ):
Read:
Temp. Zuluft 1: A5000
Temp. Zuluft 2: A4998
% Drehzahl Zuluft: A4984
Temp. Abluft 1: A4994
Temp. Abluft 2: A4996
% Drehzahl Abluft: A4986
CO2 - Konzentration: A4992 (in ppm)
Luftfeuchtigkeit: A4990 (in %r.F.)
Luftqualität VOC: A4522 (in %)
Venting mode: I4582 (0 - 5; See under write the mappings)

Write:
Day mode: writeTags?returnValue=true&n=1&t1=I4582&v1=0
Night mode: writeTags?returnValue=true&n=1&t1=I4582&v1=1
Timer mode: writeTags?returnValue=true&n=1&t1=I4582&v1=2
Party mode: writeTags?returnValue=true&n=1&t1=I4582&v1=3
Vacation mode: writeTags?returnValue=true&n=1&t1=I4582&v1=4
Bypass mode: writeTags?returnValue=true&n=1&t1=I4582&v1=5

**Comment by sibbi77** [comment]
How do these tags relate to the already supported Ecovent tags: "3:HREG400000", "3:HREG400002", ... ?

**Comment by Polooo2** [comment]
I got these tags from the webUI of the Ecotouch. Never saw that these were already in the binding. I tried these (seem to be Modbus registers) using the readTag get request and they return the same value as the UI tags. 

Some time ago I got the Modbus documentation for Ecovent from Waterkotte. You can access all Modbus values with the format "3:HREG4000XXX".

See:
https://drive.google.com/file/d/1hxPxnYWB1Cz7Jiu6_drZtaQUHR8shGOl/view?usp=sharing

**Comment by Polooo2** [comment]
Looking at the code there is only reading of EcoVent values. No changing of the venting mode. As soon as I have my system upgraded to OH3 I can give it a try and create a PR

**Comment by sibbi77** [comment]
a small test: you can now read and write the EcoVent Mode with the new pre-release:
https://github.com/sibbi77/openhab2-addons/releases/tag/ecotouch-3.0.0-3
no text yet, only the numbers 0-5

**Comment by Polooo2** [comment]
Was able to test it today on a clean OH3 instance. I was able to install it without any issues. Linking the EcoVent Mode channel to an item worked and it properly displayed the current venting mode. After changing the mode on the EcoVent it got updated to the correct value.

Nice work!
