### ISSUE TITLE
OH 3 integration

### ISSUE THREAD

**Issue by Graefer** [sibbi77/openhab2-addons#2]
Hi, thank you very much for this addon (may be the most important for me). I just updated from OH 2 to OH 3, missing this add on desperately, now. I put org.openhab.binding.ecotouch-3.0.0.jar in /usr/share/openhab/addons but still not visible in the OH 3 UI. Any idea what I can do to make your add on work with OH 3?
Thank you!

**Comment by sibbi77** [comment]
You should now be able to add a thing.
Go to Settings/Things:
![grafik](https://user-images.githubusercontent.com/1971630/103568117-4a7a8780-4ec5-11eb-8f69-d42a6de0b1f8.png)
press the blue "+" in lower right corner:
![grafik](https://user-images.githubusercontent.com/1971630/103568172-65e59280-4ec5-11eb-8b56-c620a8fdb8ed.png)
you should now be able to add the thing:
![grafik](https://user-images.githubusercontent.com/1971630/103568228-7dbd1680-4ec5-11eb-9c46-1608ee7479d4.png)
If this does not work, get back to me, then we need to check the log file.

**Comment by Graefer** [comment]
Fixed permissions with openhabian-config and did a reboot. Still no Ecotouch binding or thing visible to add. Any help?

**Comment by sibbi77** [comment]
I'm sorry, I've no Raspberry Pi to test on. I've reinstalled my docker based openhab-3.0.0 with clean folders and copied the binding into the `addons` folder. It took some time (approx 60 s), but then it worked like I've described above.

**Comment by sibbi77** [comment]
btw. on my system the addons folder is here: `/openhab/addons`

**Comment by sibbi77** [comment]
please try the new pre-release: https://github.com/sibbi77/openhab2-addons/releases/tag/ecotouch-3.0.0-2

**Comment by Graefer** [comment]
No success. Probably due to my incompetence concerning OH3.

**Comment by Graefer** [comment]
Do you know when your add on will officially be merged in OH3?

**Comment by sibbi77** [comment]
I did not yet file a merge request. I wanted to wait until all the major problems have been solved. And the documentation has to be improved before the merge (this one: https://github.com/sibbi77/openhab2-addons/blob/ecotouch-3.0.0/bundles/org.openhab.binding.ecotouch/README.md). I expect the merge to happen not before mid February.

**Comment by Graefer** [comment]
Ok, finally managed it by downloading the jar with 'wget' instead of copying it from my pc (so it was probably a permission issue). In OH3 the thing is labelled "online". Great!
However, I do not get any data, everything is NULL. The items are defined with a text file, e.g.
`Number:Temperature HeatPump_Temperature_aussen24h   "Wärmepumpe Außentemperatur 24h [%.1f °C]"   <temperature>  {channel="ecotouch:geo:460cc18ef3:temperature_outside_24h" }
`
Any help?

**Comment by sibbi77** [comment]
Are you sure, the id of your thing is 460cc18ef3? I've tested your line and it works for me:
![grafik](https://user-images.githubusercontent.com/1971630/104807758-97bdf980-57e1-11eb-951a-5bdde02f1a31.png)

**Comment by Graefer** [comment]
Thank you for trying. Yes, I think so, the ID is correct.
![image](https://user-images.githubusercontent.com/26072184/104819007-23a84380-582b-11eb-8a89-afa2da35b438.png)

The log is warning:
java.lang.NoSuchMethodError: 'org.openhab.binding.ecotouch.internal.EcoTouchTags[] org.openhab.binding.ecotouch.internal.EcoTouchTags.values()'
	at org.openhab.binding.ecotouch.internal.EcoTouchHandler.lambda$1(EcoTouchHandler.java:184) ~[?:?]

**Comment by Graefer** [comment]
Just fixed permissions - now it works!

**Comment by Buerius** [comment]
Hey, thank for writing the binding. Also for me, it would be one of the most important ones ;-).  But unfortunately I have the same issue. The thing state change to online, but the value of the items is null. I tried to add items with text files and direct in openhab. But the result ist the same. Any idea? 

![Waterkotte](https://user-images.githubusercontent.com/78444031/106653580-48c0e400-6597-11eb-9565-0b22ab6b2a1a.PNG)

**Comment by sibbi77** [comment]
there is a new build from upstream: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.ecotouch/3.1.0-SNAPSHOT/org.openhab.binding.ecotouch-3.1.0-SNAPSHOT.jar
can you try that one?

**Comment by Buerius** [comment]
Thank a lot. The update solved the issue!

![Waterkotte2](https://user-images.githubusercontent.com/78444031/106663276-c4c12900-65a3-11eb-949d-c43d36868de7.PNG)

**Comment by Graefer** [comment]
Yes, 3.1.0 works! Thanks!
