### ISSUE TITLE
Info über EVU-Sperre, Kühlung, Token

### ISSUE THREAD

**Issue by Graefer** [sibbi77/openhab2-addons#4]
Hallo, 
1) die Wärmepumpe zeigt auf dem Display auch die EVU-Sperre an. Läßt sich sich diese Info eigentlich auch mit dem Binding auslesen bzw. gibt die Wärmepumpe diese Info über die API überhaupt weiter?
2) Das Gleiche gilt für die Meldung, ob geheizt oder (passiv) gekühlt wird (Stellung des Motorventils). Dies kommuniziert die Wärmepumpe über das Tag I52. Aber mit welchem Channel lese ich das mit dem Binding aus? state_alarm?
3) Könnte das Binding den aktuellen Cookie-Token ausgeben, damit man ggf. noch mit anderen Geräten gleichzeitig Zugriff haben könnte?
Danke

**Comment by sibbi77** [comment]
Hallo,

die Wärmepumpe listet die Abschaltung unter den Betriebs-Unterbrechungen auf. Beispiel:

`Number HeatPump_Interruptions      "Interruptions"          <settings> (Heatpump) { channel="ecotouch:geo:heatpump:interruptions" }`

Bit 2 ist für die externe Abschaltung zuständig. Wenn die Abschaltung aktiv ist, wird Bit 2 gesetzt. Das bedeutet, der Werte wechselt von 0 auf 4.

Tag I52 steht für die Alarmmeldungen, es ist eher I51 (state). Damit kann das ganze Register gelesen werden. Einzelne Werte bekommt man über die Channel:

- state_sourcepump
- state_heatingpump
- state_evd
- state_compressor1
- state_compressor2
- state_extheater
- state_alarm
- state_cooling
- state_water
- state_pool
- state_solar
- state_cooling4way

Das Token rauszugeben halte ich für keine so gute Idee. Man kann sich aber von mind. zwei Geräten gleichzeitig verbinden.

**Comment by Graefer** [comment]
Ok, vielen Dank, funktioniert jetzt wie gewünscht. Insbesondere die Info über Bit 2 beim Tag 53 für EVU-Sperre hat mir sehr gut weitergeholfen!
